### ISSUE TITLE
Get into markdown a little bit

### ISSUE THREAD

**Issue by synthead** [githubschool/code-vienna#4]
As suggested, let's chat about markdown for a few!

Suggested by @Waelazar :+1:

**Comment by ghost** [comment]
Taco - Mexican Restaurant
2352 Wiener Neudorf | SCS - Shopping City Süd | Ebene 0 | Top 174 | Telefon: +43 2236 614 09
1210 Wien | Ignaz Köck Straße 1 | SCN - Shopping Center Nord | Top 112 | Telefon +43 1 271 79 79
www.taco.at | Email: office@taco.at
Webdesign © by PeterDesign 2014 | www.peter-design.at

This is my Colleague Rami info, so if you lost, Good Luck
